### ISSUE TITLE
Is it possible to have music?

### ISSUE THREAD

**Issue by vanfanel** [h4mu/rott94#6]
Hi there, Tamas!

I have discovered your ROTT SDL2 port, and it runs great on the Raspberry Pi thanks to being an excellent SDL2 port, so it gets "free" hardware fullscreen scaling via GLES2 renderer in SDL2. Good! :D

However, I miss ROTT's trademark cheesy music. I see no mention on the README.md or original docs, and looking at the code I don't see any OPL emulation or support for OGGs. etc.
Is this planned somehow? 

Thanks!

**Comment by h4mu** [comment]
Hi Manuel,

Thanks for the kind words, I'm glad you like it. The music is working for me, do other apps have sound, do you have the volume settings correct? Are you running the game in a folder you have write access to? I checked the source code (dukemusc.c) and instead of playing the music from buffers  the music is saved to MIDI files before being loaded and played with SDL_Mixer. According to the documentation SDL Mixer can play OGG files too if you want to change the player code in ROTT.

**Comment by vanfanel** [comment]
@h4mu I got it to work, it's a matter of building SDL2_Mixer with Timidity support and that's it, music plays thru SDL2_Mixer midi :)

Is there a way to make the game work at the original 320x240 resolution instead of 640x480 that's using now? I tried to set iGLOBAL_SCREENWIDTH adn iGLOBAL_SCREENHEIGHT to 320 and 240 respectively, but it's still hi-res.
320x240 would be necessary for low-cpu machines like the Raspberry PI, where I ultimately want to have ROTT SDL2.

**Comment by h4mu** [comment]
I'd think it used Mode-X (hence the filename modexlib.c for the rendering code) but yes the height does seem to be set at 200 px. It doesn't matter much with SDL2 though as we're just rendering to a texture that gets scaled to the screen by the hardware. The screen updates are called directly from the game loop so perhaps you can add some delays in there or try to enable vertical blank in drirc or in the appropriate environment variable.

I didn't think RPi would have performance problems with it since its original hardware requirements were 386DX 40 MHz CPU :) It runs fine on my 1 GHz Allwinner A13 tablet but its screen doesn't have a big resolution.

**Comment by vanfanel** [comment]
@h4mu : Thing is, what's the intended framerate of this game? DOS Doom for example is 35FPS... Is ROTT the same? Can it be "convinced" to run at a different framerate?

**Comment by h4mu** [comment]
I don't know, sorry.
