### ISSUE TITLE
many thanks for this wonderful ROTT port for android!!

### ISSUE THREAD

**Issue by oe7twj** [h4mu/rott94#8]
works fine on my Pixel tablet
works fine on my GPD XD plus

*happy*

**Comment by oe7twj** [comment]
All three versions runs very fine.

Is it possible to play "DarkWar" WAD files?

**Comment by h4mu** [comment]
Hi, thanks for the feedback, I'm glad you like it.Yes, the non-shareware versions can play the darkwar game content. When you run the app it will tell you where to copy the files but it will be something like /sdcard/Android/data/io.github.h4mu.rott94/files. You will need to copy the WAD, RTS, RTC, RTL files into that directory.

It should also be possible to play custom levels but that is currently not supported on Android because it doesn't have command line arguments and we'd have to create a new menu for picking the files etc.

**Comment by oe7twj** [comment]
oh yes …

It is not nessecary to have a new menu.
But it would be nice, to make it possible, to set commandline Arguments.
Maybe only read command line arguments from a text file, if this file does exists.

So it would be possible to have different directories with different comand line Arguments.


"Dark War" is Incredible!
Try it  … :-)


Thank you very much for ROTT on Android!

**Comment by h4mu** [comment]
Hi, I created a new release with user level support: https://github.com/h4mu/rott94/releases/tag/v0.86-beta
